// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/amartery/statSaver/internal/app (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "github.com/amartery/statSaver/internal/app/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockRepository) Add(arg0 *models.StatisticsShow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockRepositoryMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRepository)(nil).Add), arg0)
}

// ClearStatistics mocks base method
func (m *MockRepository) ClearStatistics() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearStatistics")
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearStatistics indicates an expected call of ClearStatistics
func (mr *MockRepositoryMockRecorder) ClearStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearStatistics", reflect.TypeOf((*MockRepository)(nil).ClearStatistics))
}

// ShowOrdered mocks base method
func (m *MockRepository) ShowOrdered(arg0 *models.RequestForShow) (*[]models.StatisticsShow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowOrdered", arg0)
	ret0, _ := ret[0].(*[]models.StatisticsShow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowOrdered indicates an expected call of ShowOrdered
func (mr *MockRepositoryMockRecorder) ShowOrdered(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowOrdered", reflect.TypeOf((*MockRepository)(nil).ShowOrdered), arg0)
}
