// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/amartery/statSaver/internal/app (interfaces: Usecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "github.com/amartery/statSaver/internal/app/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockUsecase) Add(arg0 *models.RequestForSave) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockUsecaseMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUsecase)(nil).Add), arg0)
}

// ClearStatistics mocks base method
func (m *MockUsecase) ClearStatistics() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearStatistics")
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearStatistics indicates an expected call of ClearStatistics
func (mr *MockUsecaseMockRecorder) ClearStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearStatistics", reflect.TypeOf((*MockUsecase)(nil).ClearStatistics))
}

// Show mocks base method
func (m *MockUsecase) Show(arg0 *models.RequestForShow) (*[]models.StatisticsShow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", arg0)
	ret0, _ := ret[0].(*[]models.StatisticsShow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Show indicates an expected call of Show
func (mr *MockUsecaseMockRecorder) Show(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockUsecase)(nil).Show), arg0)
}
